function plot_detections(stamp, data, max_det, color, name, marker)
    if nargin < 6
        marker = 'o';
    end

    if marker == '-'
        plot(stamp(:,1:max_det), data(:,1:max_det), marker, ...
            'Color', color, ...
            'HandleVisibility','off');
        plot(NaN, NaN, marker, ...
            'Color', color, ...
            'DisplayName', name);
    else
        plot(stamp(:,1:max_det), data(:,1:max_det), marker, ...
            'MarkerFaceColor', color, ...
            'MarkerEdgeColor', color, ...
            'HandleVisibility','off');
        plot(NaN, NaN, marker, ...
            'MarkerFaceColor', color, ...
            'MarkerEdgeColor', color, ...
            'DisplayName', name);
    end
end