function [cam_only,cam_enh] = splitCamYolo(data)

    emptyDetectionStruct = struct( ...
        'sens_stamp', NaN, ...
        'stamp', NaN, ...
        'x_rel', NaN, ...
        'y_rel', NaN, ...
        'z_rel', NaN, ...
        'yaw_rel', NaN, ...
        'x_map', NaN, ...
        'y_map', NaN, ...
        'z_map', NaN, ...
        'yaw_map', NaN, ...
        'count', NaN, ...
        'valid_yaw', NaN, ...,
        'source_type', NaN, ...
        'max_det', NaN ...
    );

    [split_det, source_types] = splitBySourceType(data);

    cam_only = emptyDetectionStruct;
    cam_enh = emptyDetectionStruct;
    for i=1:numel(source_types)
        split_det{i}.max_det = max(sum(~isnan(split_det{i}.x_rel')));
        if(source_types(i) == 3); cam_only = split_det{i}; end
        if(source_types(i) == 4); cam_enh = split_det{i}; end
    end
end

